### PR TITLE
Add sanctions for NSO Liberator weapons

### PR DESCRIPTION
**Pull request by carlst99**

### CODE REVIEW

**Review by fredkilbourn — APPROVED** [review]
I'm fine with this.

**Comment by cooltrain7** [comment]
Interested in giving the duster, the drake, and the hyena none?

**Comment by fredkilbourn** [comment]
@carlst99 you have to merge in the latest changes into your repo to resolve conflicts

**Comment by fredkilbourn** [comment]
> Interested in giving the duster, the drake, and the hyena none?

@cooltrain7 Not sure I follow your question completely, but his changes are in line with how the other Lib weapons are assigned.

**Comment by cooltrain7** [comment]
> 
> 
> > Interested in giving the duster, the drake, and the hyena none?
> 
> @cooltrain7 Not sure I follow your question completely, but his changes are in line with how the other Lib weapons are assigned.

Oh I mean why are those weapons specifically flagged as none and not flagged as gunner or air?

**Comment by fredkilbourn** [comment]
> > > Interested in giving the duster, the drake, and the hyena none?
> > 
> > 
> > @cooltrain7 Not sure I follow your question completely, but his changes are in line with how the other Lib weapons are assigned.
> 
> Oh I mean why are those weapons specifically flagged as none and not flagged as gunner or air?

Because they are considered cheese or meme weapons (at the time, duster is bad now), meant to be excluded from stat.  Many of the DA sanctions are based on excluding low-skill high-reward weapons altogether.  I am personally fine with maintaining that mentality somewhat with this.

**Review by cooltrain7 — APPROVED** [review]

**Comment by cooltrain7** [comment]
@carlst99 Can you do a resync with master and we should be all good.

**Comment by carlst99** [comment]
@cooltrain7 should be done 👍

**Pull request merged**
