### PR TITLE
Change MAX weapons to "max" sanction

### PR DESCRIPTION
**Pull request by brakenium**
This PR changes the sanction-list MAX weapons to be assigned to the "max" sanction for use with MAX specific statistics

### CODE REVIEW

**Comment by fredkilbourn** [comment]
@brakenium you need to update your pull based on the new master

**Comment by fredkilbourn** [comment]
I don't mind the idea of making a category for max, personally, but I don't know who really wants to promote max play/stats.

**Comment by brakenium** [comment]
@fredkilbourn You mean like this? I never really worked with pull requests

**Comment by fredkilbourn** [comment]
Yep looks better, just have to wait on someone else to weigh in on their opinion I don't really want to do all this unilaterally.  As other pulls are merged in you may have to re-do yours again.

**Comment by cooltrain7** [comment]
I think its all about giving options, so having as many ways of grouping weapons/items into sets is always a good thing. So having a max filter, even if some won't personally use it is still important.

**Review by fredkilbourn — APPROVED** [review]
I'm fine with this

**Review by cooltrain7 — APPROVED** [review]
Good with me also!

**Pull request merged**
