### PR TITLE
Community weapons review

### PR DESCRIPTION
**Pull request by fredkilbourn**
Signed-off-by: Fred Kilbourn <fred@fredk.com>

### CODE REVIEW

**Comment by cooltrain7** [comment]
This looks great! I do think that variant weapons should have the same sanction as the parent. I.e the NS-10 and the NS10B should have the same sanction. Thoughts?

**Comment by fredkilbourn** [comment]
i agree.  this is just a base commit that exactly reflects the last da sanctions.  I imagined using this as a baseline and then making a series of commits against it for revisions that can provide a trackable history.  I'd like to have most changes signed off on by a few members of the community so we have a consensus on how it should look.

**Comment by fredkilbourn** [comment]
I'd you accept this, we can make prs against it that first catch the low hanging fruit and then we can make the harder decisions.

**Comment by fredkilbourn** [comment]
I just thought this format was more human readable for review and revision, the  we can port it back to a better machine format.

**Pull request merged**
