### PR TITLE
Added Faction IDs and Is Vehicle Weapon and new File with redone sanction and Item Category

### PR DESCRIPTION
**Pull request by BlackJackGear**
Im not 100% happy with everything yet but here is 99% of the Stuff so far.

### CODE REVIEW

**Comment by cooltrain7** [comment]
I persoanlly don't want another variation of the sanctions. I think the sanctions list should be _the_ sanctions list. Where there is a single file that represents the sanctions. Any variants are based off that one file for maintaining consistancy.

**Comment by BlackJackGear** [comment]
I only included the sanctions I changed in the new file the original one only has updated faction ids and is vehicle weapons

**Comment by fredkilbourn** [comment]
I'd also tend to agree against adding any alternate sanctions interpretations.  We're trying to create a unified interpretation across the whole community so that all stat sites/bots will come up with approximately the same results.

I would request taking sanction-list_redone_sanction_and_category.csv out of the PR and items you differ from the master list on should be made as smaller per-item PRs so we can come to a shared consensus, if possible.

I still have to review the proposed changes to the primary list, give me a minute on that.  Also, I'm seeing a lot of my entries were plugged in with defaulting to '0' for vehicle weapon if it wasn't set.  It should really be blank up front to better see how your changes alter the base format.  I'm going to update the master in this respect and you will likely have to rebase yours accordingly once I've done that.  I'll reply here when I'm finished.

**Comment by fredkilbourn** [comment]
@BlackJackGear I've merged in the change I just mentioned in my last comment https://github.com/cooltrain7/Planetside-2-API-Tracker/pull/102

**Comment by cooltrain7** [comment]
Feel free to re-open this pull if/when the above changes are made.

**Pull request closed without merging**
