### PR TITLE
Github action for building construction and weapons list

### PR DESCRIPTION
**Pull request by brakenium**
I made a GH action for building the csv and JSON lists in Construction/ and Weapons/ using their respective list.js scripts. I don't have much experience with these actions, only made one once before. So any feedback is appreciated.

The action works on a push to the master and gh-actions (unsure if this should be out, I used it for testing) branches. And then only to the list.js, csv source and workflow file changes. Once the files are build it commits and pushes them to the repo (one for each folder).

I'm aware this includes a lot of commits from my previous PR but I'm not aware of a way to keep those out of here. So if there's a way to keep those out I'd gladly hear it!

### CODE REVIEW

**Comment by fredkilbourn** [comment]
Nice, no idea how / if it works personally, but I just got back from vacation and I'll try taking a look this week.

**Comment by brakenium** [comment]
To test it I just push a change to one or multiple of the csv files in my fork. I believe you can setup an actions runner locally but I'm not sure if that allows you to test or just run actions from a repo on it.

**Comment by fredkilbourn** [comment]
I don't know if I'll have the bandwidth to test this out any time soon.  @cooltrain7 you have time to play with it?

**Comment by cooltrain7** [comment]
> 
> 
> I don't know if I'll have the bandwidth to test this out any time soon. @cooltrain7 you have time to play with it?

Oh... I had no idea this came in... yea I'll take a peak at it.

**Pull request merged**
