### PR TITLE
Ant guns to 'gunner' to match others

### PR DESCRIPTION
**Pull request by carlst99**
Additionally, mining lasers to 'none'

### CODE REVIEW

**Comment by fredkilbourn** [comment]
Looks good to me, this would be one worth asking the greater public about though I don't know if Ant was ever excluded for a reason or if it should be okay in the gunner class.  TBH gunner class isn't very important to people so it probably doesn't matter.

**Comment by carlst99** [comment]
> this would be one worth asking the greater public about though I don't know if Ant was ever excluded for a reason

Yeah good point. My thought process was that it's exactly the same weapons as what has been sanctioned on other vehicles, and I couldn't see a good reason to exclude the ANT while the Sunderer is included.

**Comment by carlst99** [comment]
Oops. Poor git practice, apologies. That commit shouldn't be here

**Comment by fredkilbourn** [comment]
> Oops. Poor git practice, apologies. That commit shouldn't be here

@carlst99 yeah might wanna roll that back or delete this PR and recreate.  need to do all your pulls from separate branches on your end.

**Comment by carlst99** [comment]
Rolled back. Been a while since I used VCS anywhere but within my own repos :smile:

**Comment by fredkilbourn** [comment]
I posted a link on Discord #api-dev to see if anyone has an opinion.  We'll see.

**Comment by Bentheburrito** [comment]
This sounds good to me, +1

**Review by cooltrain7 — APPROVED** [review]
I don't have any problems with this - Almost all of the weapons as said above are used on other vehicles already.

**Review by fredkilbourn — APPROVED** [review]
alright, fine with me

**Comment by fredkilbourn** [comment]
@carlst99 you have to merge in the latest changes into your repo to resolve conflicts

**Comment by carlst99** [comment]
@fredkilbourn should be good now 👍

**Pull request merged**
