### PR TITLE
Sanctions: Add infantry-explosive type

### PR DESCRIPTION
**Pull request by fredkilbourn**
Move all guns with under-barrel grenade launchers to new `infantry-explosive` type.  Explosive attachments on weapons skew accuracy, kdr, kpm, ivi, shots per kill, more?  Perhaps they should be separated from the pure `infantry` sanction into their own `infantry-explosive` sanction?  Proposing this instead of excluding them outright as this will affect a good number of weapons.

Initial reasoning and discussion found on [Planetside Community Developers Discord](https://discord.com/channels/1019343142471880775/1019346740320665650/1071101044702072952).

Some points of discussion and TODO:
* Any other weapons missing still that should be changed?
* Archer is now explosive, but was originally classified as `infantry`.  Should this be changed too?
* What about including previously excluded weapons like crossbows as `infantry-explosive` now instead of `none`?

[sanction-list.csv is easiest way to view the changes](https://github.com/cooltrain7/Planetside-2-API-Tracker/pull/154/files#diff-62165882658285bae05b4110b0b30832dd66b938d7db2f240dc886be8424d000)

### CODE REVIEW

**Review by cooltrain7 — APPROVED** [review]
I'm pretty happy with this. I'm all for explosive capable weapons being tagged like this. I think yes to the Archer being moved, and yes to crossbows over none. I think any sanction is better than none.

**Comment by fredkilbourn** [comment]
> I'm pretty happy with this. I'm all for explosive capable weapons being tagged like this. I think yes to the Archer being moved, and yes to crossbows over none. I think any sanction is better than none.

I've added xbows and archers to `infantry-explosive`.  Just need to see if we're still missing anything at this point either from the `none` or `infantry` category to be moved to `infantry-explosive`.

**Comment by fredkilbourn** [comment]
This [commit ](https://github.com/cooltrain7/Planetside-2-API-Tracker/pull/154/commits/e8cd3a89a7f63e33cd9ff6b4adf93aeb51ff8a2a#diff-62165882658285bae05b4110b0b30832dd66b938d7db2f240dc886be8424d000) is based this [query:](https://census.lithafalcon.cc/get/ps2/item?name.en=Grenade%20Launcher&c:lang=en&c:limit=10000&c:show=name.en,item_id&c:join=item_attachment%5Eon:item_id%5Eto:attachment_item_id%5Eshow:item_id\(item%5Eon:item_id%5Eto:item_id%5Eshow:name.en\)) 

This list of items were added, need to confirm they are truly explosive based:
```
6009891,Assault Rifle,0,AR-101,0,infantry
7104,Assault Rifle,0,NC9 A-Tross,2,infantry
7125,Assault Rifle,0,SABR-13,3,infantry
7129,Assault Rifle,0,TORQ-9,3,infantry
7170,Carbine,0,AC-X11,2,infantry
6009895,Carbine,0,CB-200,,infantry
7211,Carbine,0,Pulsar C,1,infantry
6010047,Scout Rifle,,BAR-200,,infantry
6011257,Scout Rifle,,BAR-ARX Feynman,,infantry
```

**Comment by fredkilbourn** [comment]
@RemainNA, @Lampjaw this is getting close to completion, do you have any input/feedback?

**Comment by Lampjaw** [comment]
No feedback from me

**Comment by fredkilbourn** [comment]
Keep in mind, this will have a semi-large impact on infantry IVI scores by moving a lot of guns that used to be `infantry` to the new `infantry-explosive` group.

**Comment by RemainNA** [comment]
All looks good to me!  Moving crossbows and Archers to explosive makes sense.  The impact on IVI too, since there's no good way to filter out the UBGL kills otherwise.

**Pull request merged**
