### PR TITLE
Final sanction wrap-up

### PR DESCRIPTION
**Pull request by fredkilbourn**
One final commit to wrap up the remaining missing sanctions, figure its easier to discuss in one place.

**Changes:**
* All Patriot and Triumph Flare Guns (`infantry` to `none` to match Deep Freeze and Candy Cannon)
  * **Edit: Updated to `meme` per suggestions**
* Ectoblaster and Soldier Soaker (`none`, to match other special event pistols)
  * **Edit: Updated to `meme` per suggestions (CandyCannon & Deep Freeze too)**
* NS-AM8 Shortbow (`infantry` to match other archers)
* NS-30 Tranquility (`infantry` to match other battle rifles)
* Havoc Missiles (`air` to match other ESF A2A lock-ons)
  * **Edit: Havocs and existing A2A pods updated to `none` per suggestions**
* Wyrm (`none` to match M18 Locust/M20 Kestrel/Antares LC)
  * **Edit: Wyrm/Locust/Kestrel/Antares updated to `air` per suggestions**
* NEST Launcher (`none` to match all other flash weapons, lack of similarity to other armor types)

**My Thoughts:**
These were the hardest changes to make decisions on for me, and require the most input from the community.

The special event pistols had a lot of inconsistency in the original DA list, with some as `infantry`, some as `none`, and some as uncategorized.  I think moving them all to `none` makes sense from a sanction perspective, they don't belong mixing with normal pistol stats.

Shortbow is basically a worse Archer, so I figure that's fine moving to `infantry` to join the Archer.

Tranquility is a toss-up, not sure what people think of it, but I don't feel it's particularly oppresive so thowing in with `infantry` makes sense.

Havoc and Wyrm were both really hard to say, I ended up putting them both in with their closest relatives but could definitely be open to discussion.

NEST Launcher also I really have no idea, but I feel it doesn't belong with `armor` so probably `none`.

Signed-off-by: Fred Kilbourn <fred@fredk.com>

### CODE REVIEW

**Comment by fredkilbourn** [comment]
@carlst99 @KatsuPatrick @brakenium @Bentheburrito Tagging you here for input since you've given some in the past.

**Comment by carlst99** [comment]
Shifting the 'meme' guns to `none` looks good to me. They produce stats that don't give a fair representation of the player.
Also agree with A7 weapons matching their counterparts; they're all a bit gimmicky but not ridiculously so.
No thoughts on the NEST Launcher.

Looking at those air sanctions leaves me a little confused.

First and foremost, (and bear with, this is not a change you've made with this PR) classing the long-range noseguns (Antares, Kestrel and Locust) as `none` seems very out of line with the other two nosegun types. They are certainly not overpowered, and comparatively slightly underpowered for targeting ESFs. I don't believe they produce stats that are out of line with any other ESF weapons. I personally see no reason to not have these sanctioned as `air`.

Marking the Havocs and A2A lockons pods as `air` seems reasonable given their extremely niche area of effectiveness. However they won't produce constructive accuracy statistics. Further, Hornets should probably match the sanctions of these weapons. They all have similar function (lock/laser guided, long reload, high alpha damage bar Havocs) and are all considered to have cheese potential.

Wyrms should be marked as `air` imo. They are a higher risk, higher reward weapon, requiring good leading or getting right in under that Dalton 😛. Would definitely be happy to see them match the sanctions of Havocs and A2A locks though, given they are all designed for similar purposes.

**Comment by brakenium** [comment]
The event/meme weapons should have `none` as their type since they will only make stats less reliable for the given player. These are not/can not be used in a serious manor and won't show what the player is actually capable off. 

The Shortbow should definitely be `infantry`. It's a solid stalker weapon because of the stealth aspect and thus should not be discounted. As for the explosive bolt, I have it equipped all the time while driving a harasser but am rarely able to make an impact with it in a way that it would skewer stats.

The Tranquility is well balanced, the slowness aspect is very useful when you have the skill. If you don't have the skill, you still need to double headshot to kill making this primarily a skill based weapon. This double headshot makes it less usable than the vandal, the slowdown effect makes up for this in a balanced manor. This should be classified as `infantry`.

The NEST Launcher I haven't used much. Since other flash weapons are infantry this should be the same, most people will consider the Javelin a flash anyway. So this should be `none` to match flash, unless flash weapons are changed.

To come back to the meme/event weapons. It might be worth looking into making a separate `meme` sanction for them. Some people might want to have these statistics available just for the fun of it. I'm open to better names for this sanction though.

I won't comment on the air since I don't have enough experience, especially not in an ESF.

**Comment by fredkilbourn** [comment]
I agree with the nose guns not making sense as `none` and the havocs/wyrms should both me `air` as well.  I'll change the PR accordingly.

**Comment by fredkilbourn** [comment]
Also updating the event pistols to the `meme` category as suggested.

**Comment by Bentheburrito** [comment]
Further on the air sanctions: I agree with @carlst99, there's really no reason Kestrel/Locust/Antares can't be `air`. It takes a decent degree of change in play-style to take advantage of the larger magazine and have cheese potential (at least in ESF-ESF fights). Even then it's very possible to counter.

If air locks are `air` I think the Wyrm definitely warrants the tag, too. Like Carl said, it takes more effort to actually be effective and/or an actual threat.

I know it's not up for discussion, but locks/Hornets being `air` doesn't seem like a good fit to me. To be effective, one has to:
1) Hover
2) Track and click (in the case of air locks) or click and track (Hornets)
No leading and little to no movement required, meaning their stats don't really reflect how well one can actually fly. (Full disclaimer, I'm a dirty skyknight, so my A2A biases definitely show here.) I can understand that their niche use against the larger aircraft may not sway stats much, but any sway is still worth considering imo.

**Comment by fredkilbourn** [comment]
> I know it's not up for discussion, but locks/Hornets being `air` doesn't seem like a good fit to me. To be effective, one has to:
> 
> 1. Hover
> 2. Track and click (in the case of air locks) or click and track (Hornets)
> 
> No leading and little to no movement required, meaning their stats don't really reflect how well one can actually fly. (Full disclaimer, I'm a dirty skyknight, so my A2A biases definitely show here.) I can understand that their niche use against the larger aircraft may not sway stats much, but any sway is still worth considering imo.

@Bentheburrito I tend to agree with you and was surprised that DA had A2A locks sanctioned as `air` in their list.  I agree with DA already having assigned hornets and coyotes to `none` and I believe they will stay that way.  I feel if we changed A2A locks to `none` we'd need to also change havocs to match.  Think we should push down this avenue now or try and make a revision down the road?  I don't wanna be too aggressive.

**Comment by Bentheburrito** [comment]
> I feel if we changed A2A locks to none we'd need to also change havocs to match.

@fredkilbourn Yeah for sure, by "air locks" I meant both A2A locks and Havocs - sorry for the ambiguity.

I don't think changing those two to `none` will be very controversial. If someone shares a good argument for locks to be `air` down the road we could always switch back, yeah?

**Comment by fredkilbourn** [comment]
Ok havocs and 1st gen A2A pods are now `none`.  How's this shaping up guys getting closer to commit?

**Comment by carlst99** [comment]
Totally agree with air lockons being `none` 👍. All looks pretty good to me now.

**Comment by SamFissure** [comment]
I like the openness of the devs here.  I agree with most of this, especially the prior comment about locks not generating good statistics.

**Comment by fredkilbourn** [comment]
that's the goal, make something all the 3rd party devs can agree on and share so stats are the same with every website/bot/etc.

**Comment by fredkilbourn** [comment]
That said, if nobody has any more input I'll be merging this commit soon tonight.

**Pull request merged**
