### PR TITLE
Assign reskins to base sanction type

### PR DESCRIPTION
**Pull request by fredkilbourn**

### CODE REVIEW

**Comment by cooltrain7** [comment]
Want to keep this open to keep adding to it or is it good to go?

**Comment by fredkilbourn** [comment]
> Want to keep this open to keep adding to it or is it good to go?

I'd really love to have a comment or approval from someone else in the community first especially @lampjaw and/or fisu since they have the two bigger stat sites going.

**Comment by fredkilbourn** [comment]
@cooltrain7 did you see <https://discord.com/channels/251073753759481856/451032574538547201/844239642966622268> and <https://discord.com/channels/251073753759481856/451032574538547201/844239784600010832>?

Might be worth setting up some reviewers that can be tagged for this, ask for volunteers in #api-dev?

**Comment by fredkilbourn** [comment]
I personally think this should be cut and dry though, all the assignments here are based on other assignments with different skins.

**Review by cooltrain7 — CHANGES_REQUESTED** [review]
Can you do a quick fix for the max changes from the other PR?

**Comment by Lampjaw** [comment]
It makes sense to me though would it not make more sense to just remove all weapons that are not sanctioned? Why keep a list of items irrelevant to context of the list?

**Comment by fredkilbourn** [comment]
> It makes sense to me though would it not make more sense to just remove all weapons that are not sanctioned? Why keep a list of items irrelevant to context of the list?

DA kept a list of none before too, the best feature of it (imo) is to have an idea what's new and needs to be addressed when DBG adds new stuff.

**Comment by fredkilbourn** [comment]
> Can you do a quick fix for the max changes from the other PR?

@cooltrain7 just fixed it

**Comment by Lampjaw** [comment]
> > It makes sense to me though would it not make more sense to just remove all weapons that are not sanctioned? Why keep a list of items irrelevant to context of the list?
> 
> DA kept a list of none before too, the best feature of it (imo) is to have an idea what's new and needs to be addressed when DBG adds new stuff.

Oh I see, that makes sense then if you're using an automated way to update the list and then having a human curate it later 👍

**Comment by fredkilbourn** [comment]
> > > It makes sense to me though would it not make more sense to just remove all weapons that are not sanctioned? Why keep a list of items irrelevant to context of the list?
> > 
> > 
> > DA kept a list of none before too, the best feature of it (imo) is to have an idea what's new and needs to be addressed when DBG adds new stuff.
> 
> Oh I see, that makes sense then if you're using an automated way to update the list and then having a human curate it later 👍


@lampjaw we could keep this master list with the extra 'none' assignments but strip them out for the file that would be deployed for machine use

**Comment by Lampjaw** [comment]
> > > > It makes sense to me though would it not make more sense to just remove all weapons that are not sanctioned? Why keep a list of items irrelevant to context of the list?
> > > 
> > > 
> > > DA kept a list of none before too, the best feature of it (imo) is to have an idea what's new and needs to be addressed when DBG adds new stuff.
> > 
> > 
> > Oh I see, that makes sense then if you're using an automated way to update the list and then having a human curate it later 👍
> 
> @Lampjaw we could keep this master list with the extra 'none' assignments but strip them out for the file that would be deployed for machine use

That would be ideal, thanks!

**Comment by cooltrain7** [comment]
> 
> Oh I see, that makes sense then if you're using an automated way to update the list and then having a human curate it later +1

I think that should definitely be the goal.

**Comment by cooltrain7** [comment]
> 
> @Lampjaw we could keep this master list with the extra 'none' assignments but strip them out for the file that would be deployed for machine use

So do we want to create an alt file for that use now?

**Comment by fredkilbourn** [comment]
> > @Lampjaw we could keep this master list with the extra 'none' assignments but strip them out for the file that would be deployed for machine use
> 
> So do we want to create an alt file for that use now?

We should soon, maybe get a few of the initial changes done first.

**Comment by Lampjaw** [comment]
> > @Lampjaw we could keep this master list with the extra 'none' assignments but strip them out for the file that would be deployed for machine use
> 
> So do we want to create an alt file for that use now?

I'd take advantage of git actions to generate that for you automatically every time it's updated

**Comment by fredkilbourn** [comment]
> > > @Lampjaw we could keep this master list with the extra 'none' assignments but strip them out for the file that would be deployed for machine use
> > 
> > 
> > So do we want to create an alt file for that use now?
> 
> I'd take advantage of git actions to generate that for you automatically every time it's updated

I was just looking into that but I'm not versed with them.  It would be a perfect solution though if someone could help build one.

**Pull request merged**
